### PR TITLE
NStepQ working

### PR DESCRIPTION
**Pull request by lake4790k**
Fixed the N step Q agent. Logic was good, just made the mistake (intended as speed optimization...) of not `forward`ing the same state before `backward`ing it which is incorrect as torch caches state from `forward` necessary for the `backward`. Catch now converges with n-step in less than 1 minute (was 2 mins with 1 step Q). Double Q also works with both, will run longer pong experiment to compare with and without.

### CODE REVIEW

**Comment by Kaixhin** [comment]
FYI I showed Tom Schaul a plot (attached below) from prioritised experience replay running on Frostbite and he commented that he'd never seen collapses in performance like that before. I've just started tests on Beam Rider to see if this is caused by PER code or the relatively simple DDQN code is similarly affected. So there's a reasonable chance that there is a bug floating around which might be affecting the performance of either everything or ER-based code.

scores

**Comment by lake4790k** [comment]
I haven't seen such profile either in my async experiments (mainly pong), few times rather longer gradual performance decline and then gain.

I read the original DM code and your code many many times line by line... My async learner code is simpler as it deals with one method at a time and async doesn't do batches either, so easy to verify vs the pseudocode in the papers. I always saw that your code is completely in line with the original DM code in the simple DQN case as is mine. (at least your learning code Im pretty sure is the same, the replay memory you have is a bit different, but random sampling should not be an issue) So I would be extremely surprised if everything was affected (including async), or if even simpler ER was affected and less surprised if its something in prioritized ER, which is much harder...

But will keep on eye, haven't run many games yet, so could be surprises. This whole area is a really difficult one...

**Comment by lake4790k** [comment]
@Kaixhin one thing came to my mind about your chart: if a single game episode is long (either hard to die or net can play for long), it could be that during validation steps there would be only a few (even just one or two, etc) episodes. If sometimes the net manages to play a really long single episode lasting through the validation then it would achieve a high avg validation score (single episode score divided by 1). If it dies just before the end of validatnno avg score would drop to half right away (1. episodes score / 2).

If frostbites had long episodes compared to the validation period, that could explain the chart, I don't if that is the case...?

**Comment by lake4790k** [comment]
@Kaixhin This single episode idea is probably not the case, I looked at frostbite, 1-step and n-step async quickly got to around 220 / 200 avg score, but probably won't be able to reach beyond as per papers only prioritized performs well. But around the score of 200 I see 100s of episodes in a validation, so the distorted avg idea doesn't explain your chart.

Btw frostbite seems like a good testcase for testing the async n-step dueling combo that I haven't tried yet.

Also not easy to reproduce the DM scores when they report "avg of best 3 of 50 runs" scores. They must have had 100s of machines to run their experiments, without that one needs to get lucky.

**Comment by Kaixhin** [comment]
@lake4790k Yep just checked my logs and I'm still averaging about 150 episodes at the end of training for Frostbite. I'm currently running hardware tests - a CPU run on my test machine and a single GPU run on my personal machine. The test machine has all GPUs running in parallel, some running Atari experiments and some running other people's code.

With what Tom said about variance, Frostbite might require a few runs, but yes it'll be a good test for n-step. DRQNs also do well thanks to their ability to preserve temporal information. Disappointing to hear that results can be variable, but yes they do have lots of machines so it's certainly feasible for them.

Btw I've set you up as a collaborator so you can work directly on this repo as you see fit. Just don't force push to master ;)

**Comment by lake4790k** [comment]
@Kaixhin thanks for adding me, I'll only push to async, but would still do PR for master.

**Comment by Kaixhin** [comment]
So far the CPU and GPU run look have the weird drops, so doesn't look like a hardware issue. Also trying Beam Rider with the DDQN and PER - DDQN seems to learn well and doesn't have drops, but PER does. So pretty confident that it's a PER issue.

One thing to note by comparing training curves with the ones in the PER paper is that it looks like the DDQN baseline is using the normal DQN hyperparameters, and not the tuned hyperparameters (which the PER networks use). As evidence the difference for Frostbite as reported in the DDQN paper is 258.3 versus 1448.1. In PER the plot shows convergence for the baselines around 300.

**Pull request merged**
