### PR TITLE
Use SeqLSTM

### PR DESCRIPTION
**Pull request by JoostvDoorn**
I am rewriting some stuff to use SeqLSTM instead of FastLSTM with the recurrent option. This will make things faster, especially if people start using longer histories. Depends on torch/nn#861, and  torch/nn#889.

### CODE REVIEW

**Comment by Kaixhin** [comment]
Looks great! And should make it easier if there are future improvements to LSTMs as they'll probably come from having a sequential unit. Given https://github.com/torch/nn/pull/860, `Bottle.lua` can be removed from this PR?

**Comment by lake4790k** [comment]
In `Model` for async the net was built without a Sequencer before. Now `Model` builds `SeqLSTM` for async as well, so logic would change there. I'm not sure if will be correct, but it's fine for now, I'll have a look later anyway when extending recurrent mode to all async agents (only 1 step is considered currently).

**Comment by Kaixhin** [comment]
@JoostvDoorn are we ready to merge this now (pending resolving any conflicts)?

**Comment by JoostvDoorn** [comment]
@Kaixhin I think so. I will clean this up, and prepare for merge.

**Comment by Kaixhin** [comment]
@JoostvDoorn Any updates?

**Comment by JoostvDoorn** [comment]
Sorry for the delay. I cleaned up the code, will be running some tests to see if it still works.

**Comment by JoostvDoorn** [comment]
The code as such will break async, it is probably fine if async uses FastLSTM and use SeqLSTM for recurrent. @Kaixhin what is your take on this?

**Comment by Kaixhin** [comment]
Seeing as recurrency was only supported for one-step async, I think it's fine to focus on the DQN for now. That said, eventually it would be good to get recurrent support for all async agents, even if they need different implementations.

**Comment by JoostvDoorn** [comment]
It should now work for recurrent DQN, and should not break async. Sorry for taking such a long time, I am not working with this code at the moment.

**Pull request merged**
