### PR TITLE
Enable travis testing

### PR DESCRIPTION
**Pull request by lake4790k**
Created `.travis.yml` config and added a really simple test to start. @Kaixhin you'll need to log in and enable `Atari` on https://travis-ci.org and we can add the status image to `README.md`

I  checked my fork on travis, it passed fine executing the test. We should add more tests going forward for the unit testable things.

### CODE REVIEW

**Comment by Kaixhin** [comment]
Nice idea - I'll sort out the badges later today in the `refactor` branch. It would be good if you can have a look at that branch because I'm hoping to merge that into master soon - just waiting a bit longer on a Beam Rider test to confirm that prioritised experience replay is finally working. Still only barely poked around your async code but hope to go over that relatively soon.

I haven't looked at the Travis docs for ages but if we can somehow remove the need to install Torch and its dependencies using Docker, I'll make [`kaixhin/cuda-torch-plus`](https://github.com/Kaixhin/dockerfiles/tree/master/cuda-torch-plus) an automated build.

**Comment by lake4790k** [comment]
@Kaixhin docker would be great, [seems](https://docs.travis-ci.com/user/docker/) to be supported on travis. Will have a look at `refactor`!

**Comment by lake4790k** [comment]
looked through `refactor` commits, all make sense!

**Comment by Kaixhin** [comment]
Thanks - aiming to merge into `master` by the end of the week once the PER experiment has run for longer. Will then have to familiarise myself with your `async` code properly and will continue working on the `refactor` branch.

**Comment by Kaixhin** [comment]
Set up Docker builds for [`kaixhin/cuda-torch-mega`](https://hub.docker.com/r/kaixhin/cuda-torch-mega/) so we should be able to use it for Travis soon!

**Comment by Kaixhin** [comment]
[Successful build](https://hub.docker.com/r/kaixhin/cuda-torch-mega/builds/bcg2qzt3fgrnoqbpauhohty/) (minus `luaposix`), but should be enough for current testing.

**Pull request merged**
