### PR TITLE
async 1stepQ

### PR DESCRIPTION
**Pull request by lake4790k**
Initial attempt at one step q. Seems to work with catch, haven't tried ale yet.

### CODE REVIEW

**Comment by Kaixhin** [comment]
Nice work! I'll merge it into this branch so that other people can have a look. I eventually hope to look over your code properly and see if it can be merged with the existing files - will probably create another branch to do that work in. If you could try ALE that would be great.

**Comment by lake4790k** [comment]
@Kaixhin wanted add some remarks yesterday, but got exhausted finishing the code.

I tried to reuse as much of your awesome experience replay (ER) based code, but was also not easy to add the different async logic, so I added new files as well with the new logic that had to be organized differently.

I think the existing ER code would also benefit from refactoring, especially the huge loop in `main.lua` should be broken up into classes. There are 3 things there: training, validation and evaluation, if these were separate, would be easier to reuse between ER and async. Also the visualisation logic could be a completely separate class, so one only needs to look at one aspect at a time. But I also didn't want to do the refactoring for the ER as you may want to do it differently.

Once the refactoring is done much of the copy paste I did from your code can be get rid of.

This is only an initial async version, I need to add a lot of stuff still:
- only 1-step-Q is implemented, will add the other ones as well, esp. A3C as the most powerful
- the varied epsilon policy is missing, I'll add that as it is important to generate experiences that are as diverse as those sampled from the ER memory
- shared rmsprop is missing
- many basic things are missing, eg. saving/resuming, V and error plotting, etc, these are needed, the saliency feature may not fit well with the many threads, maybe enough to have in ER
- I have doubleQ, duelling, and I also want to add PAL. Bootstrapped is probably not a good fit and obviously prioritized doesn't combine
- the async 1/n Q learning logic itself is not minibatch based, so could stay separate from the ER implementation

Would be awesome if you could look through the code, there could issues, I only pushed because it converged for catch well, eg:
`./async_run.sh demo -threads 8`

The performance is interesting. The original ER version converges up to around 0.8 with both CPU and GPU, for me CPU is around 30 mins. With multiple threads this async reached 0.8 in less than 5 mins.

But also a single thread reaches 0.8 in less than 10 mins, which makes me think why ER is much slower as it's a similar algo in that case. I have a little [lua class](https://gist.github.com/lake4790k/eb9344a578ac57486c02993043c966b3) I can profile with which part of the code takes up the execution time, would be interesting to check. It could be it's not that are ER converges more slowly, it is rather executing slower, so its progressing slower. Sampling from a large memory may slow down things quite a bit, cpu caches don't work and much of the data needs to come from memory. Also the code always uses the BinaryHeap even without prioritised replay, haven't checked, but could be inserting in the heap always causes an overhead of walking through the heap, when it's not really needed?

I'll try with ALE, that would be the real test (for that the epsilon policies are surely needed), hope it will work fine in the torch/multithreaded environment, I'm a bit afraid that during creation of xitari I had add locking to fix occasional crashes, but then during stepping it looked good without locking.

So still a lot of work...

**Comment by Kaixhin** [comment]
If you think you can handle refactoring then go for it - you have a better idea than I do about what is required to get it ready for async methods. This'll probably be the only major change as other work is more algorithmic. If you can give a list of what changes you plan to make in advance then I can provide some feedback.

As I suspected, the conclusion of the paper mentions that ER can be added back in for a greater performance boost (it's just that this method allows learning online). So potentially all of these improvements could be used together (hence this codebase). Worth seeing if the code can be future-proofed to use both the online learning and ER.

ER definitely suffers from memory issues. With ALE the speed once the ER is full is significantly slower than when training begins. Yes there's a small overhead (since the data structure should be efficient) with using the queue when not needed - fixed that. Actually PER might improve the caching of the ER since it's no longer uniform sampling/somewhat predictable.

Great work - keep at it!

**Comment by lake4790k** [comment]
@Kaixhin what I plan now is to
- add the basic missing features to async (saving net/resuming, avg V)
- reproduce one ALE result from the paper, eg. breakout
- unify with the ER codebase: will open an issue with my proposed refactoring plan first

**Comment by Kaixhin** [comment]
@lake4790k Sounds like a good plan. I'll try to look at your code properly in the meantime.

**Pull request merged**
