### PR TITLE
A3C

### PR DESCRIPTION
**Pull request by lake4790k**
Works with catch, started experiment with pong, started learning there as well.

### CODE REVIEW

**Comment by lake4790k** [comment]
It learnt `pong` quite well, reached almost +20 in 12h with 11 hyperthreads (5.5 real cores):

scores

This is of course much faster than 1-step Q and more importantly matches the DM A3C score/time curve for 8 real cores.

**Comment by Kaixhin** [comment]
Great to hear it matches. For completeness will you be able to add the SARSA agent as well? Otherwise you're pretty much done (unless you want to look at `rnn` for A3C LSTM before refactoring for master)?

**Comment by lake4790k** [comment]
@Kaixhin Sure, good idea, just pushed Sarsa as well (`catch` converges faster than 1 step Q). Yes slowly time to think about merging async and master... I'll start a few more experiments and prepare a proposal for the code merge!

**Comment by lake4790k** [comment]
I had second thoughts about the Sarsa implementation. The way the paper has it is not completely clear on this, it says the target is:

```
y = r + gamma * Q(s_, a_, theta_)
```

"where `a_` is the action taken in `s_`". What I did is to make an e-greedy decision for `a_` with for `s_` with `theta_`, but then go on make another e-greedy with `theta` as well when `s_` becomes `s` on the next step.

I thought it would make more sense to use `theta` to produce an e-greedy `a_` on `s_` and just use `theta_` to compute its `Q` for the target and then use the `a_` selected in the next step, this also would be more in line with the Sutton book Sarsa algo.

But with catch my original implementation converges well, but this "corrected" one does not converge, so I assume my original solution is the correct one.

**Comment by lake4790k** [comment]
I'm running `breakout` with A3C, looks good. This is for 18 hours (the first 3 hours are missing as my server froze and had to resume with the weights, but lost the validation data):

scores

I'm using 11 hyperthreads and the curve looks more like their 16 real core curve than the 8, so than nice.

But then I got a

```
[10: ERROR - 2016_05_22_15:57:30] - bad argument #2 to '?' (invalid multinomial distribution (sum of probabilities <= 0) at /root/tor
ch/pkg/torch/lib/TH/generic/THTensorRandom.c:120)
stack traceback:
        [C]: at 0x7f4b27e2edd0
        [C]: in function 'multinomial'
        ./A3CAgent.lua:52: in function <./A3CAgent.lua:33>
        [C]: in function 'xpcall'
        ./AsyncMaster.lua:209: in function <./AsyncMaster.lua:208>
```

not sure what numerical issue this is. I suspect probabilities became NaN for some reason. I resumed, will see if happens again. Only happened after 18 hours of running, bit strange. I suspect computing `log` on the probability caused it, I will add a some small number to make sure all probs are really > 0.

**Comment by Kaixhin** [comment]
I would replace the code inside the `if not terminal then` with the following, where `action_` is literally the action taken in the next state (so this update can't be run on the actual transition). I think the best way to do this is to update the previous state instead, and do the current state as well on `terminal`.

``` lua
Y = Y + self.gamma * self.policyNet:forward(state_)[action_]
```

**Comment by Kaixhin** [comment]
Ergh best try and log the probabilities somewhere to check. Worth going over [issues concerning `multinomial`](https://github.com/torch/torch7/issues?utf8=%E2%9C%93&q=multinomial) and seeing if any might affect you?

**Comment by lake4790k** [comment]
@Kaixhin re: Sarsa, thats what I tried exactly and did not converge. I think as well that should be Sarsa... I'll have a try again, maybe I made some other mistake. (but my solution now converges better than all the others for catch, maybe its a new good method...)

re: multinomial, had a look at the issues, there were some that appear somewhat related (issues with using `FloatTensor` as input), but those have been fixed already. I'll add checking and logging where exactly bad values come from.

**Comment by Kaixhin** [comment]
@lake4790k Sorry misunderstood you. If you're using e-greedy then as e approaches 0 you'll simply be doing the Q-learning update rule. Haven't come across a hybrid like this, but I wouldn't be surprised if someone has tried it before... Best to check the different implementations on Atari games to see what matches up.

**Comment by lake4790k** [comment]
@Kaixhin Using e-greedy there I took from the [Sutton book](https://webdocs.cs.ualberta.ca/~sutton/book/ebook/node64.html) as they referred to it, but as I said its not entirely clear what they mean in the paper, I'll try again.

**Comment by Kaixhin** [comment]
@lake4790k Had a friend who is very familiar with SARSA take a look, and he agrees with what I suggested/what you did. However, I spotted that you don't seem to be using the target network for the target (instead using the policy network). If that is the case then you may want to review your other agents to check that they're using the target networks appropriately.

**Comment by lake4790k** [comment]
@Kaixhin thx for looking, I think I'm using the target net properly: in the freak SARSA version I have in `aync` branch [these lines](https://github.com/Kaixhin/Atari/blob/async/SarsaAgent.lua#L18-L22) will add the value of `s_` using the target network (`QCurr` is populated by `eGreedy` using the target network I'm passing as an argument). Also in the version that should be what we agree Sarsa really is I used the target net when I tested it.

I started a `pong` experiment with both, but either seemed to progress too well (freak a bit, the "correct" one not at all). I'll return to SARSA bit later as now I'm looking at LSTM for `async` methods.

Re: the `invalid multinomial distribution (sum of probabilities <= 0)` error, it was what I suspected: rarely policy gives action probabilities `{1,0,0}` taking the `log` of gives `-inf` that infects the weights with `nan`s. So I'll add a tiny float to probs to prevent this, so A3C should be fine.

**Comment by Kaixhin** [comment]
@lake4790k If `QCurr` is populated with the target network, then yes `Y = Y + self.gamma * self.QCurr[action_]`, but `Q_state` should surely come from the policy network itself (as at the moment `Q_state = self.QCurr[action]`)?

Well done on resolving the multinomial issue :+1: Code comments appreciated.

**Comment by lake4790k** [comment]
Yes when I do `Q_state = self.QCurr[action]`, `QCurr` continains the policy network Qs, it is populated by the `eGreedy` method with whatever network I pass it.

Generally I dislike comments, many times they state the obvious or get out of sync with code unmaintained, only use them in non obvious cases... but actually there's not much obvious code in `Atari`, so agree good to add them often...

**Pull request merged**
